version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build

  artifacts:
    files:
      - build/**/*
    discard-paths: yes
  #build:
    #commands:
      #- aws s3 sync build/ s3://<your-bucket-name> --delete
